all:
	pdflatex gemm_unb_var1_ws_answer.tex
	pdflatex gemm_unb_var2_ws_answer.tex
	pdflatex gemm_unb_var3_ws_answer.tex
	pdflatex gemm_unb_var4_ws_answer.tex
	pdflatex gemm_unb_var5_ws_answer.tex
	pdflatex gemm_unb_var6_ws_answer.tex
	pdflatex gemm_blk_var1_ws_answer.tex
	pdflatex gemm_blk_var2_ws_answer.tex
	pdflatex gemm_blk_var3_ws_answer.tex
	pdflatex gemm_blk_var4_ws_answer.tex
	pdflatex gemm_blk_var5_ws_answer.tex
	pdflatex gemm_blk_var6_ws_answer.tex
	pdflatex symm_l_unb_var9_ws_answer.tex
	pdflatex symm_l_unb_var10_ws_answer.tex
	pdflatex symm_l_unb_var1_ws_answer.tex
	pdflatex symm_l_unb_var2_ws_answer.tex
	pdflatex symm_l_unb_var3_ws_answer.tex
	pdflatex symm_l_unb_var4_ws_answer.tex
	pdflatex symm_l_unb_var5_ws_answer.tex
	pdflatex symm_l_unb_var6_ws_answer.tex
	pdflatex symm_l_unb_var7_ws_answer.tex
	pdflatex symm_l_unb_var8_ws_answer.tex
	pdflatex symm_l_unb_var9_ws_answer.tex
	pdflatex symm_l_unb_var10_ws_answer.tex
	pdflatex symm_l_unb_var9_ws_answer.tex
	pdflatex symm_l_unb_var10_ws_answer.tex
	pdflatex symm_l_blk_var1_ws_answer.tex
	pdflatex symm_l_blk_var2_ws_answer.tex
	pdflatex symm_l_blk_var3_ws_answer.tex
	pdflatex symm_l_blk_var4_ws_answer.tex
	pdflatex symm_l_blk_var5_ws_answer.tex
	pdflatex symm_l_blk_var6_ws_answer.tex
	pdflatex symm_l_blk_var7_ws_answer.tex
	pdflatex symm_l_blk_var8_ws_answer.tex
	pdflatex symm_l_unb_var9_ws_answer.tex
	pdflatex symm_l_unb_var10_ws_answer.tex
	pdflatex symv_unb_var1_ws_answer.tex
	pdflatex symv_unb_var2_ws_answer.tex
	pdflatex symv_unb_var3_ws_answer.tex
	pdflatex symv_unb_var4_ws_answer.tex
	pdflatex symv_unb_var5_ws_answer.tex
	pdflatex symv_unb_var6_ws_answer.tex
	pdflatex symv_unb_var7_ws_answer.tex
	pdflatex symv_unb_var8_ws_answer.tex

clean:
	rm -f *.synctex.gz *.mtc* *.aux *.log *.maf

clean_pdf:
	rm -f *.pdf
